services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ad12345#
      POSTGRES_DB: web-builder
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 15431:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Ad12345#
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  redis:
    image: redis
    ports:
      - 16379:6379
    volumes:
      - redisdata:/data
    command: ["redis-server", "--save", "600", "1"]

volumes:
  pgdata:
  pgadmin:
  redisdata:
